### ISSUE TITLE
Add support voor vue-router in button component

### ISSUE THREAD

**Issue by mannes-paqt** [paqtcom/graphite-design-system#136]
Using href attribute in button component 'breaks' vue-router and reloads the whole page. 

Suggest adding `to` attribute to button component so the button can be used with SPAs that use vue-router

**Comment by elwinvaneede** [comment]
You can achieve this by extending the RouterLink: https://router.vuejs.org/guide/advanced/extending-router-link.html

The SPA routing is handled with a click handler, and it falls back to an href. This is all possible with a gr-button.

I would not advise adding framework specific code in Web Components.

**Comment by mannes-paqt** [comment]
Hey Elwin, Thanks for your reply! 

Most other component libraries offer support for vue-router. It seems like pretty basic functionality and a requirement for making accessible applications (link preview, navigation for the visually impaired) this 'breaks' when using a click handler.

When using the href attribute the gr-button element already gets rendered as a link tag instead of a button, adding support for vue-router would complete this functionality.

Hope you will reconsider

**Comment by elwinvaneede** [comment]
@mannes-paqt Your welcome.

Well those are probably Vue specific component libraries, Graphite is framework agnostic. Then Graphite would theoretically also need to support all the routers that exist for React. Plus, those would all be extra dependencies and make the bundle larger, while you want to keep this as small as possible for a component library. There are also Vue applications that don't need or use Vue Router.

Vue Router's RouterLink by default renders `<a>` elements with an `href` attribute and a click handler. The click handler is what enables the client-side routing. That's perfectly accessible as long as you have an `href` attribute and a label.

But with Graphite you don't want to render a `<a>` element, but a `<gr-button>` element. That's where [extending RouterLink](https://router.vuejs.org/guide/advanced/extending-router-link.html) comes in, like I've shared before.

Working example: https://stackblitz.com/edit/vue-router-graphite?file=src/components/RouterLinkButton.vue

I'm no longer a maintainer of Graphite, since I've left PAQT. But luckily no changes are needed in Graphite for you to use Graphite together with Vue Router.

**Comment by mannes-paqt** [comment]
@elwinvaneede thanks for your reply and your example, this is very useful. 
I do think graphite could be a lot more attractive if it would support some standard vue things a bit better, ie vue-router, two-way binding through v-model .. etc. But that's something i'll take up with my colleagues here :)
For now I have a solution! :)

**Comment by elwinvaneede** [comment]
@mannes-paqt the Vue 3 wrappers support v-model. And for Vue 2 there is a custom directive: https://graphitedesignsystem.com/guidelines/components-usage/#using-a-custom-directive

@Tom-paqtcom it might be good to document how to use Graphite together with Vue Router (see my example above).
